services:
  - type: web
    name: mou-generator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    publishDirectory: ./ # Serving directly from root directory
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: FLASK_ENV
        value: production